POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5vcnBwYTEyMyIsImlkIjoiNjkzMmZmYTc3NzM5ODY5YzA3NDFhYTgwIiwiaWF0IjoxNzY0OTYyNTY4fQ.Fi2MFahV4rF7AuxzUF-9b70CXNDAKGnPLf0rtGw-VOQ

{
    "title": "Cooking with Cacish",
    "author": "Cacish",
    "url": "some random url",
    "likes": "9001"
}